name: CI

on:
  push:
    branches: [ master, feature/* ]

  pull_request:
    branches: [ master, feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install NPM Dependencies
        run: npm ci --ignore-scripts

      - name: Run Compile
        run: npm run compile

      - name: Run Tests
        run: npm run test
